Time Path partial
ZahariaAlexC/OrangeHRFramework pull request #5
Opened 2023-04-10 15:22 UTC by yonutzu

Am creat un PR. 
Rog verificare

2023-04-10 15:31 UTC, danutsendroiu requested changes

2023-04-10 15:31 UTC, danutsendroiu commented on src/test/resources/SelectorsPath/Time
> +Time module: //a[@class='oxd-main-menu-item active']
Path-ul pentru "Time Module" nu este individual

2023-04-10 15:57 UTC, StefanMdaniel approved these changes
ok

2023-04-11 10:28 UTC, AlexandruZaharia91 commented
este ok

2023-04-11 10:28 UTC, AlexandruZaharia91 approved these changes

2023-04-11 10:29 UTC, AlexandruZaharia91 commented
@yonutzu  , ready for approve

2023-04-11 13:06 UTC, danutsendroiu approved these changes
OK

2023-04-11 13:07 UTC, danutsendroiu approved these changes

2023-04-11 15:37 UTC, ZahariaAlexC approved these changes

2023-04-11 16:13 UTC, merged